name: Deploy Python Flask API to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # ✅ Allows manual redeploy from Azure Portal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: sanathana-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
